spring: 

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/study?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: deok%t4r3e2w1q
      
mybatis: 
  mapper-locations: 
  - /mappers/*.xml
    
    
